"""F5 Sandboxed executor.

Runs a generated suite with pytest in a subprocess: one file per test (a broken test cannot take
the others down), wall-clock timeout, CPU and address-space rlimits, and the sandbox conftest
(network allowlist + method guard + redacted request log). Failed tests are re-run three times
to detect flakiness. The target's server log is sliced to the run's time window.
"""

from __future__ import annotations

import json
import resource
import shutil
import subprocess
import sys
import time
from collections.abc import Callable
from pathlib import Path
from typing import Any

from agentqa import config
from agentqa.config import REPO_ROOT
from agentqa.models import HttpExchange, RunResult, TestResult, ValidatedTest
from agentqa.obs import metrics, tracing
from agentqa.target_config import TargetConfig

PRELUDE = '''"""Generated by AgentQA. Intent: {intent_id} ({category}, risk {risk}). Origin: {origin}/{tier}."""
import datetime, decimal, hashlib, hmac, json, math, re, time, uuid  # noqa: F401
from datetime import timedelta, timezone  # noqa: F401
from decimal import ROUND_HALF_UP, Decimal  # noqa: F401

import pytest  # noqa: F401

'''
CONFTEST = Path(__file__).with_name("conftest_template.py")


def _limits(cpu_s: int, memory_mb: int) -> Callable[[], None]:
    def apply() -> None:
        resource.setrlimit(resource.RLIMIT_CPU, (cpu_s, cpu_s))
        resource.setrlimit(resource.RLIMIT_AS, (memory_mb * 1024 * 1024, memory_mb * 1024 * 1024))

    return apply


def write_suite(tests: list[ValidatedTest], suite_dir: Path) -> dict[str, str]:
    """Write one file per test. Returns {test_name: intent_id}."""
    if suite_dir.exists():
        shutil.rmtree(suite_dir)
    suite_dir.mkdir(parents=True)
    shutil.copy(CONFTEST, suite_dir / "conftest.py")
    index = {}
    for vt in tests:
        header = PRELUDE.format(
            intent_id=vt.intent.id,
            category=vt.intent.category,
            risk=vt.intent.risk,
            origin=vt.intent.origin,
            tier=vt.tier,
        )
        (suite_dir / f"{vt.test.test_name}.py").write_text(header + vt.test.code, encoding="utf-8")
        index[vt.test.test_name] = vt.intent.id
    (suite_dir / "index.json").write_text(json.dumps(index, indent=1), encoding="utf-8")
    return index


def suite_config(
    target: TargetConfig, base_url: str, out_dir: Path, allow_mutations: bool
) -> dict[str, Any]:
    roles = target.auth.roles
    cfg: dict[str, Any] = {
        "base_url": base_url,
        "out_dir": str(out_dir),
        "allow_mutations": allow_mutations,
        "auth": {r: target.headers(r) for r in roles},
        "customer_id": roles["customer"].customer_id if "customer" in roles else None,
        "other_customer_id": roles["other_customer"].customer_id
        if "other_customer" in roles
        else None,
    }
    if target.webhook:
        cfg["webhook_secret"] = target.webhook.secret
        cfg["webhook_header"] = target.webhook.header
    return cfg


def _read_jsonl(path: Path) -> list[dict[str, Any]]:
    if not path.exists():
        return []
    return [
        json.loads(line) for line in path.read_text(encoding="utf-8").splitlines() if line.strip()
    ]


class Executor:
    def __init__(self, target: TargetConfig, *, reruns: int = 3) -> None:
        self.target = target
        self.reruns = reruns
        self.cfg = config.guardrails().sandbox

    def allow_mutations(self) -> bool:
        return bool(self.cfg.allow_mutations or self.target.sandbox)

    def _pytest(
        self, suite_dir: Path, out_dir: Path, base_url: str, select: list[str] | None = None
    ) -> None:
        out_dir.mkdir(parents=True, exist_ok=True)
        cfg_path = out_dir / "suite_config.json"
        cfg_path.write_text(
            json.dumps(suite_config(self.target, base_url, out_dir, self.allow_mutations()))
        )
        files = [str(suite_dir / f"{n}.py") for n in select] if select else [str(suite_dir)]
        cmd = [
            sys.executable,
            "-m",
            "pytest",
            *files,
            "-q",
            "-p",
            "no:cacheprovider",
            "-p",
            "no:randomly",
            "--rootdir",
            str(suite_dir),
            "-o",
            "addopts=",
            "--no-header",
            "--continue-on-collection-errors",
        ]
        env = {
            "AGENTQA_SUITE_CONFIG": str(cfg_path),
            "PYTHONPATH": str(REPO_ROOT),
            "PATH": "/usr/bin:/bin",
            "NO_PROXY": "*",
            "HOME": str(out_dir),
        }
        try:
            proc = subprocess.run(
                cmd,
                env=env,
                cwd=suite_dir,
                capture_output=True,
                text=True,
                timeout=self.cfg.timeout_s,
                preexec_fn=_limits(self.cfg.cpu_s, self.cfg.memory_mb),
                check=False,
            )
            (out_dir / "pytest.out").write_text(
                proc.stdout[-20000:] + proc.stderr[-5000:], encoding="utf-8"
            )
        except subprocess.TimeoutExpired:
            (out_dir / "pytest.out").write_text(
                f"TIMEOUT after {self.cfg.timeout_s}s", encoding="utf-8"
            )
            metrics.inc("agentqa_guardrail_events_total", guardrail="sandbox", action="timeout")

    def run(
        self,
        tests: list[ValidatedTest],
        base_url: str,
        out_dir: Path,
        server_log: Callable[[float], list[str]] | None = None,
    ) -> RunResult:
        with tracing.span(
            "execute", "stage", **{"agentqa.tests": len(tests), "agentqa.base_url": base_url}
        ) as sp:
            started = time.time()
            suite_dir = out_dir / "suite"
            index = write_suite(tests, suite_dir)
            main_out = out_dir / "exec"
            if main_out.exists():
                shutil.rmtree(main_out)
            self._pytest(suite_dir, main_out, base_url)
            rows = {r["test"]: r for r in _read_jsonl(main_out / "results.jsonl")}
            exchanges = _read_jsonl(main_out / "exchanges.jsonl")
            events = _read_jsonl(main_out / "guardrail_events.jsonl")
            results: list[TestResult] = []
            for name, intent_id in index.items():
                row = rows.get(
                    name,
                    {
                        "outcome": "error",
                        "message": "no result (collection error or crash)",
                        "duration_s": 0.0,
                    },
                )
                ex = [
                    HttpExchange.model_validate(
                        {k: e.get(k) for k in HttpExchange.model_fields if k in e}
                    )
                    for e in exchanges
                    if e.get("test") == name
                ]
                results.append(
                    TestResult(
                        test_name=name,
                        intent_id=intent_id,
                        outcome=row["outcome"],
                        message=row.get("message", ""),
                        duration_s=row.get("duration_s", 0.0),
                        exchanges=ex,
                    )
                )
            failed = [r for r in results if r.outcome in ("failed", "error")]
            for i in range(self.reruns if failed else 0):
                rerun_out = out_dir / f"rerun{i + 1}"
                if rerun_out.exists():
                    shutil.rmtree(rerun_out)
                self._pytest(suite_dir, rerun_out, base_url, select=[r.test_name for r in failed])
                rerun_rows = {r["test"]: r for r in _read_jsonl(rerun_out / "results.jsonl")}
                for r in failed:
                    r.reruns.append(rerun_rows.get(r.test_name, {}).get("outcome", "error"))
            ended = time.time()
            for e in events:
                metrics.inc("agentqa_guardrail_events_total", guardrail="sandbox", action="block")
                tracing.event(
                    "guardrail.sandbox", action="block", detail=e.get("detail"), test=e.get("test")
                )
            counts = {
                o: sum(r.outcome == o for r in results)
                for o in ("passed", "failed", "error", "skipped", "blocked")
            }
            sp.set_attribute("agentqa.outcomes", json.dumps(counts))
            return RunResult(
                target=self.target.name,
                base_url=base_url,
                results=results,
                started_ts=started,
                ended_ts=ended,
                server_log=server_log(started) if server_log else [],
                guardrail_events=events,
            )
